import type { DailyVideoIdea } from "@/lib/types"

const DEFAULT_NICHE = "technology"

type DailyIdeaTemplate = {
  slug: string
  title: string
  hook: string
  summary: string
  tags: string[]
  format: DailyVideoIdea["format"]
  trendType: DailyVideoIdea["trendType"]
  recommendedLength: string
  baseOpportunity: number
  baseAudienceMatch: number
  baseViews: number
  engagementAngle: string
  callToAction: string
  reason: string
}

type EngagementProfile = {
  id: "low" | "medium" | "high"
  viewMultiplier: number
  opportunityBoost: number
  audienceAdjust: number
  narrative: string
}

type ChannelProfile = {
  id: "emerging" | "growth" | "established" | "authority"
  minAverageViews: number
  maxAverageViews: number
  viewMultiplier: number
  opportunityBoost: number
  audienceAdjust: number
  narrative: string
}

export interface GenerateDailyVideoIdeasOptions {
  niche: string
  engagement: "low" | "medium" | "high"
  subscribers?: number
  averageViews?: number
  channelName?: string
}

const DAILY_IDEA_TEMPLATES: Record<string, DailyIdeaTemplate[]> = {
  technology: [
    {
      slug: "ai-workflow-upgrades",
      title: "5 AI Workflow Upgrades to Ship Projects Faster",
      hook: "Open with a split-screen before/after showing how much time the AI upgrade saves in 30 seconds.",
      summary: "Walk viewers through the AI automations powering your latest build sprint and how they stack end-to-end.",
      tags: ["ai tools", "productivity", "automation", "workflow"],
      format: "Long-form",
      trendType: "Breakout",
      recommendedLength: "8-10 minutes",
      baseOpportunity: 84,
      baseAudienceMatch: 78,
      baseViews: 24000,
      engagementAngle: "Include a live build segment so viewers can duplicate the automation in real time.",
      callToAction: "Offer a downloadable automation checklist linked in the description.",
      reason: "Search interest for AI productivity stacks is up 32% week-over-week in the tech creator niche.",
    },
    {
      slug: "coding-with-ai-pair",
      title: "I Let an AI Pair Programmer Refactor My App",
      hook: "Pose the question: ‘Would you ship code generated by AI?’ before revealing the refactor results.",
      summary: "Document the refactor session, highlight decision points, and grade what the AI got right or wrong.",
      tags: ["pair programming", "refactor", "developer vlog", "ai coding"],
      format: "Series",
      trendType: "Evergreen",
      recommendedLength: "10-12 minutes",
      baseOpportunity: 79,
      baseAudienceMatch: 82,
      baseViews: 21000,
      engagementAngle: "Layer timestamps for each refactor chapter and ask the community to vote on the best snippet.",
      callToAction: "Pin a comment asking viewers which file the AI should tackle next.",
      reason: "Developer audiences respond to behind-the-scenes rebuilds—engagement rates average 9.4% across similar videos.",
    },
    {
      slug: "edge-ai-demo",
      title: "Deploying Edge AI on a $99 Device",
      hook: "Start with the device booting in under 10 seconds and detecting a live action to prove speed.",
      summary: "Showcase the full deployment pipeline from model selection to real-world latency benchmarks.",
      tags: ["edge ai", "iot", "deployment", "tech demo"],
      format: "Long-form",
      trendType: "Breakout",
      recommendedLength: "7-9 minutes",
      baseOpportunity: 88,
      baseAudienceMatch: 74,
      baseViews: 26500,
      engagementAngle: "Include a downloadable repo or starter script so viewers can replicate the build.",
      callToAction: "Drive to your GitHub repo with a QR code overlay mid-video.",
      reason: "Edge AI uploads are spiking; completion rates stay above 52% when paired with an actionable demo.",
    },
    {
      slug: "dev-tool-roundup",
      title: "The 3 Dev Tools Saving My Team 10+ Hours Weekly",
      hook: "Rapid-fire the three tools in the first 20 seconds, then rewind to unpack each workflow.",
      summary: "Compare metrics before and after adopting the tools and share team adoption templates.",
      tags: ["dev tools", "productivity", "team workflow"],
      format: "Shorts",
      trendType: "Evergreen",
      recommendedLength: "75-90 seconds",
      baseOpportunity: 73,
      baseAudienceMatch: 86,
      baseViews: 18500,
      engagementAngle: "Prompt viewers to duet or stitch with their own stack to drive community participation.",
      callToAction: "Invite viewers to drop their top tool in a poll linked in the description.",
      reason: "Tool roundups consistently earn high save rates, signaling repeatable interest from builders.",
    },
  ],
  business: [
    {
      slug: "ai-offer-engine",
      title: "How We Built an AI Offer Engine That Closed $12K in a Week",
      hook: "Tease the revenue dashboard before explaining the funnel, then break down each automation stage.",
      summary: "Reveal the copy blocks, automations, and targeting tweaks that produced the spike in conversions.",
      tags: ["ai marketing", "offer creation", "sales funnel"],
      format: "Long-form",
      trendType: "Breakout",
      recommendedLength: "9-11 minutes",
      baseOpportunity: 86,
      baseAudienceMatch: 80,
      baseViews: 26000,
      engagementAngle: "Share a live funnel teardown and overlay the exact metrics that moved.",
      callToAction: "Drive viewers to a downloadable funnel map or Notion template.",
      reason: "Business channels with AI positioning are seeing 1.3x higher click-through compared to generic funnel content.",
    },
    {
      slug: "micro-saas-sprint",
      title: "Launching a Micro-SaaS in 48 Hours: The Sprint Plan",
      hook: "Countdown on-screen as you move from idea validation to MVP launch, capturing each milestone.",
      summary: "Cover niche validation, pricing experiments, and the launch email that triggered paying users.",
      tags: ["micro saas", "startup", "product launch"],
      format: "Series",
      trendType: "Evergreen",
      recommendedLength: "3 episodes · 8 minutes each",
      baseOpportunity: 82,
      baseAudienceMatch: 77,
      baseViews: 23000,
      engagementAngle: "Invite viewers to clone the sprint board and build alongside you in public.",
      callToAction: "Link a shared Trello/Notion board viewers can duplicate.",
      reason: "Audience watch-time spikes when founders show progress in tight timeboxes—retention often exceeds 65%.",
    },
    {
      slug: "pricing-teardown",
      title: "We Tested 4 Pricing Pages—Here’s the Conversion Winner",
      hook: "Stack the four price pages on screen and ask viewers to predict the winner before revealing the data.",
      summary: "Highlight the hypotheses behind each variation and the outcome metrics that mattered.",
      tags: ["pricing strategy", "conversion rate", "ab test"],
      format: "Long-form",
      trendType: "Evergreen",
      recommendedLength: "12-14 minutes",
      baseOpportunity: 75,
      baseAudienceMatch: 83,
      baseViews: 20500,
      engagementAngle: "Provide a downloadable testing matrix and a benchmark table to screenshot.",
      callToAction: "Ask viewers to comment which variation they would scale and why.",
      reason: "Pricing breakdowns earn high community interaction, especially when paired with transparent numbers.",
    },
    {
      slug: "newsletter-flywheel",
      title: "The Newsletter Flywheel Adding 1,000 Subscribers a Week",
      hook: "Show subscriber growth chart first, then rewind to the acquisition flywheel steps.",
      summary: "Explain acquisition partners, content cadence, and the automation that nurtures new readers.",
      tags: ["newsletter", "growth marketing", "audience building"],
      format: "Long-form",
      trendType: "Evergreen",
      recommendedLength: "8-9 minutes",
      baseOpportunity: 78,
      baseAudienceMatch: 85,
      baseViews: 22000,
      engagementAngle: "Include swipe files or scripts viewers can duplicate for their niche.",
      callToAction: "Promote a lead magnet or exclusive swipe file tied to the video.",
      reason: "Audience builders consistently bookmark newsletter flywheel breakdowns for later reference.",
    },
  ],
  lifestyle: [
    {
      slug: "habit-reset-weekend",
      title: "My 48-Hour Habit Reset Weekend Routine",
      hook: "Jump into an energetic montage that sets the pace for the two-day reset before breaking down the schedule.",
      summary: "Share the full routine, meal prep, and reflective journaling prompts that keep you consistent.",
      tags: ["habit reset", "self care", "wellness"],
      format: "Series",
      trendType: "Seasonal",
      recommendedLength: "Part 1 & 2 · 6 minutes each",
      baseOpportunity: 81,
      baseAudienceMatch: 84,
      baseViews: 24000,
      engagementAngle: "Overlay checklists viewers can screenshot and follow along with over the weekend.",
      callToAction: "Link a printable reset planner for viewers to download.",
      reason: "Weekend reset videos average a 58% completion rate among wellness-focused audiences.",
    },
    {
      slug: "healthy-desk-lunches",
      title: "5 Healthy Desk Lunches That Stay Fresh All Day",
      hook: "Open fridge-to-desk showing how the meals look after 6 hours, then teach each recipe.",
      summary: "Demonstrate prep, storage, and macros while sharing flavor swaps for dietary preferences.",
      tags: ["meal prep", "healthy recipes", "productivity"],
      format: "Long-form",
      trendType: "Evergreen",
      recommendedLength: "9-11 minutes",
      baseOpportunity: 77,
      baseAudienceMatch: 86,
      baseViews: 21500,
      engagementAngle: "Prompt the audience to vote on their favorite recipe in an on-screen poll.",
      callToAction: "Drive to a free meal plan PDF in the description.",
      reason: "Food-prep walkthroughs convert with high save/share rates when convenience is the hero.",
    },
    {
      slug: "digital-minimalist-desk",
      title: "Designing a Digital Minimalist Desk Setup",
      hook: "Reveal the clean desk first, then backtrack to show the declutter process with quick wins.",
      summary: "Talk through gear selection, intentional decor, and the mindful habits that keep clutter away.",
      tags: ["minimalism", "desk setup", "productivity"],
      format: "Long-form",
      trendType: "Evergreen",
      recommendedLength: "7-8 minutes",
      baseOpportunity: 72,
      baseAudienceMatch: 82,
      baseViews: 20000,
      engagementAngle: "Add ASMR-style b-roll sequences to encourage replay value.",
      callToAction: "Invite viewers to share their setups with a branded hashtag.",
      reason: "Minimalist setup tours continue to outperform lifestyle averages by 18% in watch time.",
    },
    {
      slug: "micro-habit-stack",
      title: "Build a 10-Minute Micro Habit Stack Before Work",
      hook: "Speed-run the full 10-minute routine, then explain the science behind each step.",
      summary: "Combine mobility, mindset, and planning prompts to help viewers feel primed before work.",
      tags: ["morning routine", "habit stack", "wellness"],
      format: "Shorts",
      trendType: "Evergreen",
      recommendedLength: "60-75 seconds",
      baseOpportunity: 74,
      baseAudienceMatch: 79,
      baseViews: 18000,
      engagementAngle: "Encourage viewers to duet or stitch their own stack and tag the channel.",
      callToAction: "Prompt comments with the habit they plan to try tomorrow.",
      reason: "Short-form routines keep retention high—viewers rewatch to memorize the steps.",
    },
  ],
}

const NICHE_ALIASES: Record<string, string> = {
  tech: "technology",
  software: "technology",
  developer: "technology",
  ai: "technology",
  coding: "technology",
  business: "business",
  marketing: "business",
  startup: "business",
  finance: "business",
  entrepreneur: "business",
  lifestyle: "lifestyle",
  wellness: "lifestyle",
  fitness: "lifestyle",
  travel: "lifestyle",
  food: "lifestyle",
}

const ENGAGEMENT_PROFILES: Record<"low" | "medium" | "high", EngagementProfile> = {
  low: {
    id: "low",
    viewMultiplier: 0.82,
    opportunityBoost: -6,
    audienceAdjust: -8,
    narrative: "Your recent engagement dipped, so we prioritized hooks that reset viewer excitement quickly.",
  },
  medium: {
    id: "medium",
    viewMultiplier: 1,
    opportunityBoost: 0,
    audienceAdjust: 0,
    narrative: "Engagement is steady—these ideas balance discovery with audience familiarity.",
  },
  high: {
    id: "high",
    viewMultiplier: 1.24,
    opportunityBoost: 7,
    audienceAdjust: 9,
    narrative: "Your audience is highly engaged, so we leaned into deeper dives and community participation.",
  },
}

const CHANNEL_PROFILES: ChannelProfile[] = [
  {
    id: "emerging",
    minAverageViews: 0,
    maxAverageViews: 5500,
    viewMultiplier: 0.76,
    opportunityBoost: 6,
    audienceAdjust: -5,
    narrative: "As an emerging creator, consistency and quick wins matter most. These ideas favour sharable moments.",
  },
  {
    id: "growth",
    minAverageViews: 5500,
    maxAverageViews: 20000,
    viewMultiplier: 0.96,
    opportunityBoost: 3,
    audienceAdjust: 0,
    narrative: "Growth-stage channels thrive on structured breakdowns that keep new viewers watching longer.",
  },
  {
    id: "established",
    minAverageViews: 20000,
    maxAverageViews: 55000,
    viewMultiplier: 1.18,
    opportunityBoost: 5,
    audienceAdjust: 4,
    narrative: "Established audiences reward expert POVs—these ideas highlight proprietary data and frameworks.",
  },
  {
    id: "authority",
    minAverageViews: 55000,
    maxAverageViews: Number.POSITIVE_INFINITY,
    viewMultiplier: 1.32,
    opportunityBoost: 8,
    audienceAdjust: 6,
    narrative: "Authority channels can sustain longer, data-rich storytelling. We dialed up depth and collaboration angles.",
  },
]

function clamp(value: number, min: number, max: number) {
  return Math.min(Math.max(value, min), max)
}

function resolveNiche(input: string): string {
  const normalized = input.trim().toLowerCase()
  if (normalized in DAILY_IDEA_TEMPLATES) {
    return normalized
  }

  for (const [alias, target] of Object.entries(NICHE_ALIASES)) {
    if (normalized.includes(alias)) {
      return target
    }
  }

  return DEFAULT_NICHE
}

function detectChannelProfile(averageViews?: number, subscribers?: number): ChannelProfile {
  const estimatedAverage = (() => {
    if (typeof averageViews === "number" && !Number.isNaN(averageViews) && averageViews > 0) {
      return averageViews
    }
    if (typeof subscribers === "number" && subscribers > 0) {
      return subscribers * 0.35
    }
    return 4000
  })()

  return (
    CHANNEL_PROFILES.find(
      (profile) => estimatedAverage >= profile.minAverageViews && estimatedAverage < profile.maxAverageViews,
    ) ?? CHANNEL_PROFILES[CHANNEL_PROFILES.length - 1]
  )
}

export function generateDailyVideoIdeas(options: GenerateDailyVideoIdeasOptions): DailyVideoIdea[] {
  const niche = resolveNiche(options.niche)
  const templates = DAILY_IDEA_TEMPLATES[niche] ?? DAILY_IDEA_TEMPLATES[DEFAULT_NICHE]
  const engagementProfile = ENGAGEMENT_PROFILES[options.engagement] ?? ENGAGEMENT_PROFILES.medium
  const channelProfile = detectChannelProfile(options.averageViews, options.subscribers)
  const channelMention = options.channelName ? ` ${options.channelName} viewers keep returning for actionable takeaways.` : ""

  return templates.map((template, index) => {
    const adjustedAudienceMatch = clamp(
      template.baseAudienceMatch + engagementProfile.audienceAdjust + channelProfile.audienceAdjust,
      0,
      100,
    )
    const adjustedOpportunity = clamp(
      template.baseOpportunity + engagementProfile.opportunityBoost + channelProfile.opportunityBoost,
      0,
      100,
    )
    const predictedViews = Math.round(
      template.baseViews * engagementProfile.viewMultiplier * channelProfile.viewMultiplier,
    )
    const opportunityScore = clamp(
      Math.round(adjustedAudienceMatch * 0.55 + adjustedOpportunity * 0.45),
      1,
      100,
    )

    const narrative = [template.reason, channelProfile.narrative, engagementProfile.narrative]
      .filter(Boolean)
      .join(" ")

    return {
      id: `${niche}-${template.slug}-${index}`,
      title: template.title,
      hook: template.hook,
      summary: template.summary,
      tags: [...template.tags],
      format: template.format,
      trendType: template.trendType,
      recommendedLength: template.recommendedLength,
      opportunityScore,
      audienceMatch: adjustedAudienceMatch,
      predictedViews,
      engagementAngle: template.engagementAngle,
      callToAction: template.callToAction,
      reason: `${narrative}${channelMention}`.trim(),
    }
  })
}
