import type { User, Video, Keyword, Competitor, TrendAlert } from "./types"

export const mockUser: User = {
  id: "1",
  name: "Alex Creator",
  email: "alex@example.com",
  channelId: "UC123456",
  channelName: "Tech Insights Daily",
  subscribers: 245000,
  totalViews: 12500000,
  joinedDate: new Date("2020-01-15"),
}

export const mockVideos: Video[] = [
  {
    id: "1",
    title: "How to Master React Hooks in 2025",
    description: "Complete guide to React Hooks with real-world examples",
    views: 125000,
    watchTime: 450000,
    likes: 8500,
    comments: 2100,
    shares: 450,
    uploadDate: new Date("2025-10-15"),
    duration: 1200,
    tags: ["react", "javascript", "web-development", "hooks", "tutorial"],
    thumbnail: "/react-hooks.jpg",
    seoScore: 92,
  },
  {
    id: "2",
    title: "Next.js 16 Features Explained",
    description: "Deep dive into Next.js 16 new features and improvements",
    views: 98000,
    watchTime: 380000,
    likes: 6200,
    comments: 1800,
    shares: 320,
    uploadDate: new Date("2025-10-10"),
    duration: 1500,
    tags: ["nextjs", "javascript", "web-development", "tutorial"],
    thumbnail: "/nextjs-16.jpg",
    seoScore: 88,
  },
  {
    id: "3",
    title: "TypeScript Best Practices",
    description: "Learn TypeScript best practices for production applications",
    views: 156000,
    watchTime: 520000,
    likes: 9800,
    comments: 2500,
    shares: 580,
    uploadDate: new Date("2025-10-05"),
    duration: 1800,
    tags: ["typescript", "javascript", "programming", "best-practices"],
    thumbnail: "/typescript-logo.png",
    seoScore: 95,
  },
]

export const mockKeywords: Keyword[] = [
  {
    id: "1",
    term: "react hooks tutorial",
    searchVolume: 12500,
    competition: 65,
    trend: 85,
    score: 88,
    relatedKeywords: ["react hooks explained", "usestate useffect", "custom hooks"],
    difficulty: "Medium",
  },
  {
    id: "2",
    term: "nextjs 16 features",
    searchVolume: 8900,
    competition: 72,
    trend: 92,
    score: 85,
    relatedKeywords: ["nextjs app router", "nextjs server components", "nextjs optimization"],
    difficulty: "Hard",
  },
  {
    id: "3",
    term: "typescript tutorial",
    searchVolume: 15600,
    competition: 78,
    trend: 70,
    score: 72,
    relatedKeywords: ["typescript basics", "typescript types", "typescript interfaces"],
    difficulty: "Hard",
  },
  {
    id: "4",
    term: "web development 2025",
    searchVolume: 22000,
    competition: 85,
    trend: 88,
    score: 78,
    relatedKeywords: ["web development trends", "frontend development", "full stack development"],
    difficulty: "Hard",
  },
]

export const mockCompetitors: Competitor[] = [
  {
    id: "1",
    channelName: "Web Dev Masters",
    subscribers: 580000,
    totalViews: 45000000,
    avgViews: 125000,
    uploadFrequency: 3.5,
    topVideos: mockVideos.slice(0, 2),
    growthRate: 12.5,
  },
  {
    id: "2",
    channelName: "Code Academy",
    subscribers: 420000,
    totalViews: 32000000,
    avgViews: 98000,
    uploadFrequency: 2.8,
    topVideos: mockVideos.slice(1, 3),
    growthRate: 8.2,
  },
  {
    id: "3",
    channelName: "JavaScript Pro",
    subscribers: 310000,
    totalViews: 28000000,
    avgViews: 85000,
    uploadFrequency: 4.2,
    topVideos: mockVideos,
    growthRate: 15.8,
  },
]

export const mockTrendAlerts: TrendAlert[] = [
  {
    id: "1",
    keyword: "AI in web development",
    trend: 156,
    category: "Emerging",
    createdAt: new Date("2025-10-20"),
  },
  {
    id: "2",
    keyword: "React Server Components",
    trend: 142,
    category: "Rising",
    createdAt: new Date("2025-10-19"),
  },
  {
    id: "3",
    keyword: "TypeScript strict mode",
    trend: 98,
    category: "Stable",
    createdAt: new Date("2025-10-18"),
  },
]

export const mockAnalytics = {
  views: 379000,
  watchTime: 1350000,
  subscribers: 245000,
  engagement: 8.2,
  ctr: 4.5,
  avgViewDuration: 3.5,
}
